#!/bin/sh
CLASSPATH=/zxing/core-3.3.3.jar:/zxing/javase-3.3.3.jar:/zxing/jcommander-1.72.jar
java -client -cp $CLASSPATH com.google.zxing.client.j2se.CommandLineRunner $*  --try_harder --multi --possible_formats DATA_MATRIX PDF_417