#!/bin/sh
# --possible_formats AZTEC CODABAR CODE_39 CODE_93 CODE_128 DATA_MATRIX EAN_8 EAN_13 ITF MAXICODE PDF_417 QR_CODE RSS_14 RSS_EXPANDED UPC_A UPC_ UPC_EAN_EXTENSION
CLASSPATH=/zxing/core-3.3.3.jar:/zxing/javase-3.3.3.jar:/zxing/jcommander-1.72.jar
java -client -cp $CLASSPATH com.google.zxing.client.j2se.CommandLineRunner $*  --try_harder --multi | tail +3 | head -1